In [87]:
import pandas as pd
import numpy as np

In [88]:
train = pd.read_csv("Train_Data (1).csv")
train=train.drop("SEQN",axis="columns")
train

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN age_group
0          2.0     2.0    35.7   110.0     2.0   150.0  14.91     Adult
1          2.0     2.0    20.3    89.0     2.0    80.0   3.85     Adult
2          1.0     2.0    23.2    89.0     2.0    68.0   6.14     Adult
3          1.0     2.0    28.9   104.0     NaN    84.0  16.15     Adult
4          2.0     1.0    35.9   103.0     2.0    81.0  10.92     Adult
...        ...     ...     ...     ...     ...     ...    ...       ...
1961       2.0     2.0    33.5   100.0     2.0    73.0   6.53     Adult
1962       1.0     2.0    30.0    93.0     2.0   208.0  13.02     Adult
1963       1.0     2.0    23.7   103.0     2.0   124.0  21.41     Adult
1964       2.0     2.0    27.4    90.0     2.0   108.0   4.99     Adult
1965       1.0     2.0    24.5     NaN     2.0   108.0   3.76     Adult

[1966 rows x 8 columns]

In [89]:
test = pd.read_csv("Test_Data (1).csv")
test=test.drop("SEQN",axis="columns")
test

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN
0         1.0     1.0    32.2    96.0     2.0   135.0  15.11
1         2.0     2.0    26.3   100.0     2.0   141.0  15.26
2         1.0     2.0    28.6   107.0     2.0   136.0   8.82
3         2.0     1.0    22.1    93.0     2.0   111.0  12.13
4         1.0     1.0    24.7    91.0     2.0   105.0   3.12
..        ...     ...     ...     ...     ...     ...    ...
307       2.0     2.0    21.9    82.0     2.0    82.0   2.54
308       2.0     1.0    33.3    95.0     2.0    77.0   6.36
309       2.0     2.0    41.5    91.0     2.0   149.0  15.52
310       2.0     2.0    22.5    82.0     2.0    93.0   1.39
311       1.0     2.0    16.1    96.0     2.0   197.0   8.57

[312 rows x 7 columns]

In [90]:
train.shape

(1966, 8)

In [91]:
train = train.dropna(subset=['age_group']).reset_index(drop=True)

In [92]:
train.isnull().sum()

RIAGENDR     18
PAQ605       13
BMXBMI       18
LBXGLU       13
DIQ010       18
LBXGLT       11
LBXIN         9
age_group     0
dtype: int64

In [93]:
train.columns

Index(['RIAGENDR', 'PAQ605', 'BMXBMI', 'LBXGLU', 'DIQ010', 'LBXGLT', 'LBXIN',
       'age_group'],
      dtype='object')

In [94]:
train["age_group"]


0       Adult
1       Adult
2       Adult
3       Adult
4       Adult
        ...  
1947    Adult
1948    Adult
1949    Adult
1950    Adult
1951    Adult
Name: age_group, Length: 1952, dtype: object

In [95]:
# from sklearn.preprocessing import OneHotEncoder

# encoder = OneHotEncoder(sparse_output=False)

# one_hot_encoded = encoder.fit_transform(train["age_group"])

train["age_group"]=train["age_group"].map({ 'Adult':0, 'Senior':1})
# test["age_group"]=test["age_group"].map({ 'Adult':1, 'Senior':0})
# ID=test["age_group"]
test

RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN
0         1.0     1.0    32.2    96.0     2.0   135.0  15.11
1         2.0     2.0    26.3   100.0     2.0   141.0  15.26
2         1.0     2.0    28.6   107.0     2.0   136.0   8.82
3         2.0     1.0    22.1    93.0     2.0   111.0  12.13
4         1.0     1.0    24.7    91.0     2.0   105.0   3.12
..        ...     ...     ...     ...     ...     ...    ...
307       2.0     2.0    21.9    82.0     2.0    82.0   2.54
308       2.0     1.0    33.3    95.0     2.0    77.0   6.36
309       2.0     2.0    41.5    91.0     2.0   149.0  15.52
310       2.0     2.0    22.5    82.0     2.0    93.0   1.39
311       1.0     2.0    16.1    96.0     2.0   197.0   8.57

[312 rows x 7 columns]

In [96]:
from sklearn.preprocessing import StandardScaler

transformer = StandardScaler()
train.iloc[: , [2,3,5,6]]=transformer.fit_transform(train.iloc[: , [2,3,5,6]])

from sklearn.preprocessing import StandardScaler

trans = StandardScaler()
test.iloc[: , [2,3,5,6]]=trans.fit_transform(test.iloc[: , [2,3,5,6]])

In [97]:
# train['SEQN', 'RIDAGEYR', 'RIAGENDR', 'PAQ605', 'BMXBMI', 'LBXGLU', 'DIQ010',
    #    'LBXGLT', 'LBXIN'].isnull()

# train.iloc[: , [2,3,5,6]]=train.iloc[: , [2,3,5,6]].fillna(train.iloc[: , [2,3,5,6]].median())
# train.iloc[: , [0,1,4]]=train.iloc[: , [0,1,4]].fillna(train.iloc[: , [0,1,4]].mode())
train=train.fillna(train.median())
test=test.fillna(test.median())
# from sklearn.impute import KNNImputer
# kimp = KNNImputer(n_neighbors=5)
# kimpp = KNNImputer(n_neighbors=5)

# train = kimp.fit_transform(train)
# train = pd.DataFrame(train)
# train

# test = kimpp.fit_transform(test)
# test = pd.DataFrame(test)
# test
# train[7]=train[7].astype(int)
train
# train.isnull().sum()



RIAGENDR  PAQ605    BMXBMI    LBXGLU  DIQ010    LBXGLT     LBXIN  \
0          2.0     2.0  1.051337  0.629474     2.0  0.757338  0.310407   
1          2.0     2.0 -1.046196 -0.625437     2.0 -0.760377 -0.820862   
2          1.0     2.0 -0.651206 -0.625437     2.0 -1.020556 -0.586630   
3          1.0     2.0  0.125154  0.270928     2.0 -0.673650  0.437240   
4          2.0     1.0  1.078578  0.211170     2.0 -0.738695 -0.097709   
...        ...     ...       ...       ...     ...       ...       ...   
1947       2.0     2.0  0.751690  0.031897     2.0 -0.912148 -0.546739   
1948       1.0     2.0  0.274977 -0.386406     2.0  2.014874  0.117089   
1949       1.0     2.0 -0.583104  0.211170     2.0  0.193616  0.975258   
1950       2.0     2.0 -0.079152 -0.565679     2.0 -0.153291 -0.704257   
1951       1.0     2.0 -0.474142 -0.147376     2.0 -0.153291 -0.830068   

      age_group  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
1947          0  
1948          0  
1949          0  
1950          0  
1951          0  

[1952 rows x 8 columns]

In [98]:
X=train.drop("age_group",axis="columns")
y=train["age_group"].astype(int)

# testX=train.drop(8,axis="columns")
# testy=train[8]
y.isnull().sum()

np.int64(0)

In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [100]:
# from imblearn.over_sampling import SMOTE
# smote = SMOTE(random_state=42)
# X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [101]:
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier(n_estimators=95, learning_rate=0.1,
    max_depth=3, random_state=0).fit(X_train, y_train)
# clf.score(X_test, y_test)

# from sklearn.tree import DecisionTreeClassifier

# tree_clf = DecisionTreeClassifier(random_state=42)
# tree_clf.fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
scores1 = cross_val_score(clf, X, y, cv=5)
scores1

array([0.84143223, 0.8516624 , 0.84102564, 0.83333333, 0.82820513])

In [102]:
from xgboost import XGBClassifier
xgb_model = XGBClassifier()

xgb_model.fit(X, y)

# y_pred = xgb_model.predict(X)
from sklearn.model_selection import cross_val_score
scores2 = cross_val_score(xgb_model, X, y, cv=5)
scores2

array([0.80051151, 0.83120205, 0.83333333, 0.82307692, 0.80769231])

In [103]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(X_train,y_train)

from sklearn.model_selection import cross_val_score
scores3 = cross_val_score(lr, X, y, cv=5)
scores3

array([0.83375959, 0.83375959, 0.83076923, 0.83846154, 0.84871795])

In [104]:
clf.score(X_test,y_test)

0.8695652173913043

In [105]:
# from sklearn.tree import DecisionTreeClassifier

# tree_clf = DecisionTreeClassifier(random_state=42)
# tree_clf.fit(X, y)
# from sklearn.model_selection import cross_val_score
# scores = cross_val_score(tree_clf, X, y, cv=5)
# scores

In [210]:
from sklearn.ensemble import RandomForestClassifier
r_clf = RandomForestClassifier().fit(X_train, y_train)

from sklearn.model_selection import cross_val_score
scores4 = cross_val_score(r_clf, X, y, cv=5)
scores4

array([0.83631714, 0.83887468, 0.83333333, 0.82820513, 0.83333333])

In [186]:
params = {
    "n_estimators":[20,50,80,100,140],
    "min_samples_leaf":[4,8,12,16,20],
    "random_state":[20,42,80]
}

from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(estimator=r_clf, param_grid=params, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)
best_params = grid_search.best_params_

In [188]:
best_params

{'min_samples_leaf': 4, 'n_estimators': 80, 'random_state': 20}

In [ ]:
from catboost import CatBoostClassifier

c_clf=CatBoostClassifier()
c_clf.fit(X_train,y_train)

from sklearn.model_selection import cross_val_score
scores5 = cross_val_score(c_clf, X, y, cv=5)
scores5

Learning rate set to 0.013708
0:	learn: 0.6836206	total: 3.72ms	remaining: 3.72s
1:	learn: 0.6747288	total: 6.13ms	remaining: 3.06s
2:	learn: 0.6660336	total: 9.52ms	remaining: 3.16s
3:	learn: 0.6566968	total: 13.5ms	remaining: 3.36s
4:	learn: 0.6477773	total: 16.8ms	remaining: 3.33s
5:	learn: 0.6398413	total: 19.9ms	remaining: 3.3s
6:	learn: 0.6317375	total: 23.3ms	remaining: 3.3s
7:	learn: 0.6244710	total: 26.8ms	remaining: 3.32s
8:	learn: 0.6168895	total: 30.4ms	remaining: 3.35s
9:	learn: 0.6098352	total: 34.1ms	remaining: 3.38s
10:	learn: 0.6041680	total: 36.4ms	remaining: 3.28s
11:	learn: 0.5984302	total: 38.4ms	remaining: 3.16s
12:	learn: 0.5919836	total: 42.2ms	remaining: 3.21s
13:	learn: 0.5855818	total: 45ms	remaining: 3.17s
14:	learn: 0.5797500	total: 47.6ms	remaining: 3.13s
15:	learn: 0.5736617	total: 50.7ms	remaining: 3.12s
16:	learn: 0.5681003	total: 53.2ms	remaining: 3.07s
17:	learn: 0.5629663	total: 55.7ms	remaining: 3.04s
18:	learn: 0.5577181	total: 58.7ms	remaining: 3.

array([0.83120205, 0.8516624 , 0.83076923, 0.84358974, 0.83333333])

In [152]:
from sklearn.svm import SVC
s_clf = SVC(kernel= 'rbf').fit(X_train,y_train)

from sklearn.model_selection import cross_val_score
scores6 = cross_val_score(s_clf, X, y, cv=5)
scores6

array([0.83887468, 0.83375959, 0.84102564, 0.83846154, 0.83846154])

In [211]:
testy = r_clf.predict(test)

In [212]:
result = pd.DataFrame({
    'age_group': testy
})

In [213]:
result

age_group
0            0
1            0
2            0
3            0
4            0
..         ...
307          0
308          0
309          0
310          0
311          0

[312 rows x 1 columns]

In [214]:
result.to_csv("submission.csv", index=False)

In [215]:
result.value_counts()

age_group
0            298
1             14
Name: count, dtype: int64